config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  devise_for :users, :controllers => {:registrations => "registrations"} do
    get '/register' => 'devise/registrations#new', :as => :new_user_registration
  end
  resources :users
  resources :wikis
  resources :charges, only: [:new, :create]

   root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  attr_accessor :active
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
   after_initialize :add_role
   def add_role
     self.role ||= "standard" if self.role.nil?
   end

   has_many :wikis, dependent: :destroy
   has_many :collaborators, through: :wikis, dependent: :destroy
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators
  belongs_to :user
  has_many :users, through: :collaborators
  accepts_nested_attributes_for :collaborators, :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  include Pundit
protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :username, :email, :password, :password_confirmation,:role)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name,
        :email, :username, :password, :password_confirmation, :current_password, :role)
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     @amount = 1500
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     # Where the real magic happens
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: @amount,
       description: "BigMoney Membership - #{current_user.email}",
       currency: 'usd'
     )
     current_user.update_attributes!(role: "premium")
     flash[:success] = "Thanks for all the money, #{current_user.email}! You are now a Premium member of Blocopedia!"

     redirect_to user_path(current_user) # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
   end

 def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "BigMoney Membership - #{current_user.name}" ,
    amount: @amount
  }
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    # setting the new_params variable
    @new_params = params.require(:user).permit(:email,:name,:role,
    :username, :current_password, :password,
    :password_confirmation)
    @change_password = true

    if params[:user][:password].blank?

      params[:user].delete("password")
      params[:user].delete("password_confirmation")
      if is_not_premium
        @new_params = params.require(:user).permit(:email,:role,:name,:username)
      else
        @new_params = params.require(:user).permit(:email,:name,:username)
      end
      @change_password = false

    end


    @user = User.find(current_user.id)

    if is_not_premium
      if params[:user][:role] == "standard" && @user.role == "premium"

        current_user.wikis.update_all(:private => false)
      end

      password_need
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)

    else
      password_need
      redirect_to "/charges/new"
    end

  end

    def is_not_premium
      params[:user][:role] == "standard" || params[:user][:role] == @user.role
    end
    def password_need
      if @change_password
        @user.update_with_password(@new_params)
      else
       @user.update_without_password(@new_params)
      end
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def create
     User.create!(user_params)
   end
   def update
     redirect_to current_account.users.find(params[:id]).tap { |user|
       person.update!(user_params)
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   }
  end

  def show
    @private_wikis = Wiki.where(user: current_user, private: true)
    @public_wikis = Wiki.where(user: current_user, private: false)
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:name,:role)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)

  end

  def edit
    @wiki = Wiki.find(params[:id])
    @wiki.collaborators.build
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  def create
    @wiki = current_user.wikis.build(wiki_params)
    #authorize @wiki
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end
  def update
    @wiki = Wiki.find(params[:id])

    params[:wiki][:collaborators_attributes].values.each do |collaborator_params|

      if collaborator_params[:active] == "1"

        @wiki.collaborators.where(user_id: collaborator_params[:user_id]).first_or_create!
      elsif @wiki.collaborators.exists?(user_id: collaborator_params[:user_id])
        @wiki.collaborators.find_by_user_id(collaborator_params[:user_id]).destroy!
      end
    end
    # for each user that is checked create a new collaborator that is associated with the current wiki
    # and destroy all collaborators that are not checked from the current wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated"
      redirect_to wiki_path
    else
      flash[:error] = "Invalid Wiki information"
      render :edit
    end
  end
  def destroy
    @wiki = Wiki.find(params[:id])

    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error destroying the wiki"
      render :show
    end
  end
  private
    def wiki_params
      params.require(:wiki).permit(:title,:body,:private)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Please click the button in order to updgrade to a premium account</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocopedia</title>
      <meta name="viewport" content="width=device=width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
         <li><%= link_to "Wikis", wikis_path %></li>
    </ul>

   <div class="pull-right user-info">
     <% if current_user %>
      Hello <%= link_to (current_user.name || current_user.email), current_user %>!
      <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
        <span class="glyphicon glyphicon-user"></span>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
        <span class="glyphicon glyphicon-log-out"></span>
      <% end %>
     <% else %>
       <%= link_to "Sign In", new_user_session_path %> or
       <%= link_to "Sign Up", new_user_registration_path %>
     <% end %>
   </div>
 <% if flash[:notice] %>
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:notice] %>
   </div>
 <% elsif flash[:error] %>
   <div class="alert alert-danger">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:error] %>
   </div>
 <% elsif flash[:alert] %>
   <div class="alert alert-warning">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:alert] %>
   </div>

 <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/users/_wiki.html.haml
%p
= link_to markdown_to_html wiki.title, wiki

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/views/users/show.html.haml
%h3  Public wikis
- if @public_wikis.empty?
  = render text: 'You have not made any public wikis yet'
- else
  = render partial: 'wiki', collection: @public_wikis, as: :wiki
%h3  Private wikis
- if @private_wikis.empty?
  = render text: 'You have not made any public wikis yet'
- else
  = render partial: 'wiki', collection: @private_wikis, as: :wiki
%p
  %p
    = link_to "New Wiki", new_wiki_path, class: 'btn btn-success'

app/views/welcome/index.html.haml
%h1 Welcome to Blocopedia!
%h2 You can make public and private wikis!!

app/views/wikis/_collaborator.html.haml
%h3 Add or Remove Collaborators from this Wiki
%table.table
  %thead
    %tr
      - ["Name", "Email", "Give Access"].each do |column|
        %th= column
  %tbody
    - User.all.each do |user|
      - unless user == current_user || user.role == "admin"
        = f.fields_for :collaborators do |c|
          %tr
            %td= user.name
            %td= user.email
            %td= c.checkbox :user
            

app/views/wikis/_form.html.haml
= form_for [wiki] do |f|
  - if wiki.errors.any?
    .alert.alert-danger
      %h4
        There are #{pluralize(wiki.errors.count, "error")}.
      %ul
        - wiki.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title"
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', placeholder: "Enter Wiki body"
  - if current_user.role == "admin" || current_user.role == "premium"
    .form-group
      = f.label :private, class: 'checkbox'
      = f.check_box :private
      Private Wiki
  %h3 Add or Remove Collaborators from this Wiki
  %table.table
    %thead
      %tr
        - ["Name", "Email", "Give Access"].each do |column|
          %th= column
    %tbody
      - User.all.each do |user|
        - unless user == current_user || user.role == "admin"
          = f.fields_for :collaborators, wiki.collaborators.where(user_id: user.id).first_or_initialize do |c|
            %tr{id: "user-#{user.id}"}
              %td= user.name
              %td= user.email
              - c.object.active = !c.object.new_record?
              %td= c.check_box :active
              = c.hidden_field :user_id
  .form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/wikis/edit.html.haml
%h1 Edit Wiki
.row
  .col-md-8
    = render partial: 'form', locals: { wiki: @wiki}

app/views/wikis/index.html.haml
%h1 Wikis
.row
  .col-md-8
    - @wikis.each do |wiki|
      .media
        .media-body
          %h4.media-heading
            = link_to (markdown_to_html wiki.title), wiki
          %small
            = wiki.body
  .col-md-4
    - if policy(Wiki.new).create?
      = link_to "New Wiki", new_wiki_path, class: 'btn btn-success'

app/views/wikis/new.html.haml
%h1 New Wiki
.row
  .col-md-8
    = render partial: 'form', locals: { wiki: @wiki}

app/views/wikis/show.html.haml
%h1= markdown_to_html @wiki.title
- if policy(@wiki).update?
  = link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success'
.row
  .col-md-8
    %p.lead= markdown_to_html @wiki.body
  .col-md-4
    - if policy(@wiki).destroy?
      = link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' }